### ISSUE TITLE
Bio.Alphabet removed from BioPython

### ISSUE THREAD

**Issue by fbertaux** [althonos/moclo#2]
`assembly.py` wants to import `IUPAC` from `Bio.Alphabet`, but was removed from Biopython:

`ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.`

**Comment by althonos** [comment]
Hi François, happy that you're still using this! I'll make an update relatively quickly, it's not a lot of work.

**Comment by althonos** [comment]
Fixed in `v0.4.7` of `moclo`, you shouldn't see this anymore once you updated.
